import type { Metadata } from "next";
import Layout from "../ssrComponent/Layout";
import Pricing from "../components/Pricing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Layout>
      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20  sm:p-20 font-[family-name:var(--font-geist-sans)] !pt-0">
        <Pricing />
      </div>
    </Layout>
  );
}
