import type { Metadata } from "next";
import Layout from "../ssrComponent/Layout"
import ApiHealthMonitor from "../components/api-health-monitor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Layout>
      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
        <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          <ApiHealthMonitor />
        </main>
      </div>
    </Layout>
  );
} 