import type { Metadata } from "next";
import Layout from "./ssrComponent/Layout";
import Link from "next/link";
import CourseInstructorDetail from "./components/screens/Videos/CourseInstructorDetail";
import RootLayout from "./ssrComponent/Layout";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  redirect("/editor");

  return (
    <>
      Home Page
    </>
  );
}
