import React, { ReactNode } from "react";
import Image from "next/image";
import "../../assets/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const AdminLayout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en" className={`${geistSans.className} ${geistMono.className}`}>
      <body className="antialiased light">
        <div className="flex h-screen">
          {/* Sidebar - Left Section */}
          <aside className="w-64 text-gray-500 p-4">
            <div className="flex items-center gap-2">
              <Image
                src="/img/logo.png"
                alt="Logo"
                width={40}
                height={40}
                className="w-10 h-10"
              />
              <h1 className="text-2xl font-bold">Unpuzzle</h1>
            </div>{" "}
            <nav>
              <ul className="space-y-2">
                <li>
                  <a
                    href="#"
                    className="block py-2 px-4 rounded hover:bg-gray-700 transition-colors"
                  >
                    Menu Item 1
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 px-4 rounded hover:bg-gray-700 transition-colors"
                  >
                    Menu Item 2
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 px-4 rounded hover:bg-gray-700 transition-colors"
                  >
                    Menu Item 3
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="block py-2 px-4 rounded hover:bg-gray-700 transition-colors"
                  >
                    Menu Item 4
                  </a>
                </li>
              </ul>
            </nav>
          </aside>

          {/* Main Content Area - Right Section */}
          <main className="flex-1 flex flex-col overflow-hidden">
            {/* Header - Top Right Section */}
            <header className="bg-white shadow-sm z-10">
              <div className="px-6 py-4 flex items-center justify-between">
                <h1 className="text-2xl font-semibold text-gray-800">
                  Dashboard
                </h1>
                <div className="flex items-center space-x-4">
                  <button className="p-2 rounded-full hover:bg-gray-100 transition-colors">
                    <svg
                      className="w-6 h-6 text-gray-500"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                      />
                    </svg>
                  </button>
                  <div className="relative">
                    <img
                      className="w-8 h-8 rounded-full"
                      src="https://via.placeholder.com/32"
                      alt="User profile"
                    />
                  </div>
                </div>
              </div>
            </header>

            {/* Content Section - Below Header */}
            <section className="flex-1 overflow-y-auto p-6 bg-gray-50">
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
};

export default AdminLayout;
