name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy unpuzzle-core to Heroku (unpuzzle-ai-backend)
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "unpuzzle-ai-backend"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "apps/unpuzzle-core"
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          dontautocreate: true

  deploy-m1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy unpuzzle-m1 to Heroku (unpuzzle-m1)
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "unpuzzle-m1"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "apps/unpuzzle-m1"
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          dontautocreate: true